apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  containers:
  - name: init
    image: dreamcacao/optimism_builder_run:latest
    command: [ "bash", "/script/init-entrypoint.sh" ]
    volumeMounts:
    - name: geth-data
      mountPath: /data
    - name: config
      mountPath: /config
    - name: script-volume
      subPath: init-entrypoint.sh
      mountPath: /script/init-entrypoint.sh
    envFrom:
    - configMapRef:
        name: env-configmap
  restartPolicy: Never
  volumes:
  - name: geth-data
    persistentVolumeClaim:
      claimName: geth-data-pvc
  - name: config
    persistentVolumeClaim:
      claimName: config-pvc
  - name: script-volume
    configMap:
      name: script-configmap