apiVersion: batch/v1
kind: Pod
metadata:
  name: geth
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: geth
        image: dreamcacao/optimism_builder_run:latest
        command: [ "bash", "/script/geth-entrypoint.sh" ]
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 8551
        volumeMounts:
        - name: geth-data
          mountPath: /data
        - name: config
          mountPath: /config
        envFrom:
        - configMapRef:
            name: env-configmap
      restartPolicy: Never
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-data-pvc
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc