apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  initContainers:
  - name: init
    image: dreamcacao/optimism_builder_run:latest
    command: [ "bash", "/script/init-entrypoint.sh" ]
    volumeMounts:
    - name: config
      mountPath: /config
    - name: geth-data
      mountPath: /data
    envFrom:
    - configMapRef:
        name: env-configmap
  restartPolicy: Never
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: config
  - name: geth-data
    persistentVolumeClaim:
      claimName: geth-data