apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth 
spec:
  replicas: 1
  selector: {}
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
        - name: geth
          image: dreamcacao/optimism_builder_run:latest
          command: ["bash", "/script/geth-entrypoint.sh"]
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 8551
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: geth-data
              mountPath: /data
            - name: config
              mountPath: /config
          envFrom:
            - configMapRef:
                name: env-configmap
      volumes:
        - name: geth-data
          persistentVolumeClaim:
            claimName: geth-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc